name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Install dependencies
        run: npm ci
      - name: Get current timestamp
        id: timestamp
        run: echo "now=$(date +%Y%m%d%H%M)" >> "$GITHUB_OUTPUT"
      - name: Restore .cache
        uses: actions/cache@v4
        with:
          path: ./.cache
          key: eleventy-fetch-cache-${{ steps.timestamp.outputs.now }}
          restore-keys: eleventy-fetch-cache-
      - name: Build site
        env:
          TMDB_ACCESS_TOKEN: ${{ secrets.TMDB_ACCESS_TOKEN }}
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v4
